Option Strict On
Imports System
Imports System.Collections.Generic
Imports System.Diagnostics
Imports System.Drawing
Imports System.Globalization
Imports System.Linq
Imports System.Windows.Forms
Imports KBot.Common
Imports KBot.Controls
Imports KBot.Domain
Imports KBot.Theming

''' <summary>
''' Load bench for <see cref="KBotChartView"/> and <see cref="KBotLaneView"/>: the same two
''' surfaces <c>AsociereForm</c> puts on screen, filled from a made-up
''' <see cref="AsociereStare"/> whose SIZE is typed in at the top — R receipts by H snapshots
''' each, plus the loose ones and the payment guides.
'''
''' <para><b>Why a bench and not the real form.</b> The real one needs a server, a commitment
''' code and a live database, so the one number that matters here — how many receipts by how
''' many snapshots — is whatever that commitment happens to hold. Here it is two spin boxes,
''' and the picture is rebuilt from them in one press.</para>
'''
''' <para><b>The data is made up; the RULES are not.</b> Everything the two surfaces read is
''' produced the way the real form produces it: a chain per receipt ordered by <c>DataH</c>,
''' the value of the WHOLE receipt at each moment (F3), a deletion row closing some chains
''' (F21), snapshots frozen by an ordonanțare, loose snapshots on the bottom lane, the end mark
''' from the receipt header, marker colour from the direction of the change, and the payment
''' guides carrying the §1.3 sum. A bench drawn from data that broke those rules would be
''' measuring a picture the operator never sees.</para>
'''
''' <para><b>What it is for.</b> Twenty snapshots on ten receipts is the ordinary case and it
''' drags. «Măsoară repictarea» paints each surface N times and reports milliseconds per frame,
''' separately, so a change can be shown to have helped instead of argued about; «repictare
''' continuă» keeps both painting so the frame rate can be watched while the operator drags a
''' marker with the mouse.</para>
''' </summary>
Public NotInheritable Class AsociereStressForm

    ' The bottom lane, and the only key that is not a receipt. Same string the real form uses.
    Private Const LOOSE_KEY As String = "LIBERE"

    ' Chart tab keys — the same two the designer writes into chart.Tabs.
    Private Const TAB_RECEIPT As String = "receptie"
    Private Const TAB_COMMITMENT As String = "angajament"

    ' The total line is not a receipt, so its key deliberately cannot collide with a series key,
    ' which always starts with "R".
    Private Const TOTAL_KEY As String = "TOTAL"

    Private Shared ReadOnly _roCulture As New CultureInfo("ro-RO")

    Private ReadOnly _log As Action(Of String)
    Private ReadOnly _originalScheme As ThemeScheme

    ' The made-up picture. Regenerated by the top band, never edited in place — the moves the
    ' operator makes by dragging live in _placement, exactly as in the real form.
    Private _state As AsociereStare

    ''' <summary>Idrh ▸ the receipt it sits on now. Absent = wherever the state put it.</summary>
    Private ReadOnly _placement As New Dictionary(Of Integer, Integer)

    Private _selectedReceipt As ReceptiePropusa

    Private ReadOnly _laneByIdrr As New Dictionary(Of Integer, KBotLane)
    Private ReadOnly _markerByIdrh As New Dictionary(Of Integer, KBotLaneMarker)

    ' The continuous-repaint clock. Interval 1 means «as often as the message queue allows»,
    ' so the rate it reaches IS the rate the two surfaces can sustain.
    Private WithEvents _animate As Timer
    Private _animating As Boolean
    Private _frames As Integer
    Private ReadOnly _fpsClock As New Stopwatch()

    Public Sub New(log As Action(Of String))
        _log = log
        _originalScheme = ThemeManager.Current
        InitializeComponent()
        _animate = New Timer() With {.Interval = 1}
    End Sub

    Private Sub OnFormShown(sender As Object, e As EventArgs) Handles MyBase.Shown
        Try
            split.SplitterDistance = Math.Max(120, split.Height \ 2)
            Regenerate()
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnFormShown", ex)
        End Try
    End Sub

    Private Sub OnClosedCleanup(sender As Object, e As FormClosedEventArgs) Handles MyBase.FormClosed
        Try
            _animate.Stop()
            _animate.Dispose()
            If _originalScheme IsNot Nothing AndAlso Not ReferenceEquals(ThemeManager.Current, _originalScheme) Then
                ThemeManager.SetScheme(_originalScheme)
            End If
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnClosedCleanup", ex)
        End Try
    End Sub

    ' ══════════════════════════════════════════════════════════════════════════
    ' The made-up picture
    ' ══════════════════════════════════════════════════════════════════════════

    ''' <summary>
    ''' Builds a state of the size typed in at the top, then draws both surfaces from it.
    ''' </summary>
    ''' <remarks>
    ''' Nothing here is random. The same numbers always produce the same picture, because a
    ''' measurement of a surface that is not the one measured a minute ago cannot be compared
    ''' with it — and comparing is the whole point of the bench.
    ''' </remarks>
    Private Sub Regenerate()
        Dim receipts As Integer = CInt(numReceipts.Value)
        Dim perChain As Integer = CInt(numSnapshots.Value)
        Dim loose As Integer = CInt(numLoose.Value)
        Dim payments As Integer = CInt(numPayments.Value)

        Dim sw As Stopwatch = Stopwatch.StartNew()
        _placement.Clear()
        _state = BuildState(receipts, perChain, loose, payments)
        _selectedReceipt = _state.Receptii.FirstOrDefault()
        Dim built As Long = sw.ElapsedMilliseconds

        Dim laneMs As Long = Rebuild(lanes:=True, chart:=False)
        Dim chartMs As Long = Rebuild(lanes:=False, chart:=True)

        lblCounts.Text = $"{_state.Receptii.Count} R × {perChain} H = {_state.Instantanee.Count} instantanee, " &
                         $"{_state.Plati.Count} repere"
        Note($"generat în {built} ms — {_state.Receptii.Count} R, {_state.Instantanee.Count} H, " &
             $"{_state.Plati.Count} plăți · benzi {laneMs} ms · grafic {chartMs} ms")
    End Sub

    ''' <summary>
    ''' The state itself: R receipts, each with a chain of H snapshots, plus the loose ones and
    ''' the payments.
    ''' </summary>
    ''' <remarks>
    ''' <para><b>The value carried is the value of the WHOLE receipt at that moment</b> (F3), not
    ''' the size of the change — that is what makes a chain a step line and what the payment
    ''' guides read back out of it.</para>
    ''' <para><b>Every third receipt ends on a header sum its chain does not reach</b>, so the
    ''' warning end mark is on screen and not only in the code that can draw it; every fifth
    ''' chain is closed by a deletion row (F21), and the first third of each chain is frozen by
    ''' an ordonanțare, which is the case that must NOT be greyed out.</para>
    ''' <para><b>A few steps deliberately change nothing.</b> A snapshot whose total equals the
    ''' one before it gets no marker colour — neither a rise nor a fall — and that branch is
    ''' worth having on screen.</para>
    ''' </remarks>
    Private Shared Function BuildState(receipts As Integer, perChain As Integer,
                                       loose As Integer, payments As Integer) As AsociereStare
        Dim state As New AsociereStare() With {
            .CodAngajament = "BANC-" & receipts.ToString(CultureInfo.InvariantCulture) & "x" &
                             perChain.ToString(CultureInfo.InvariantCulture),
            .Amprenta = "banc"
        }

        Dim origin As New Date(2026, 1, 5, 8, 0, 0)
        Dim idrh As Integer = 1

        For r As Integer = 1 To receipts
            Dim receiptDate As Date = origin.AddDays(r * 3)
            Dim rec As New ReceptiePropusa() With {
                .Idrr = r,
                .DataR = receiptDate,
                .Descriere = $"Recepția de probă {r}",
                .Sters = False
            }

            Dim total As Double = 1000 + r * 137
            Dim frozen As Integer = perChain \ 3
            Dim last As Double = 0

            For k As Integer = 0 To perChain - 1
                ' Steps of -400 … +600 in hundreds, and every so often exactly zero: the pattern
                ' repeats on purpose, so two runs of the same size are the same picture.
                Dim step_ As Double = (((k * 7 + r * 3) Mod 11) - 4) * 100.0
                total = Math.Max(50.0, total + step_)

                Dim isDeletion As Boolean = (r Mod 5 = 0) AndAlso (k = perChain - 1)
                Dim inst As New InstantaneuLegat() With {
                    .Idrh = idrh,
                    .Idrr = r,
                    .Idh = idrh,
                    .DataH = receiptDate.AddDays(k * 2).AddHours(9 + (k Mod 8)).AddMinutes((k * 13) Mod 60),
                    .Descriere = $"Salvarea {k + 1} a recepției {r}",
                    .Total = total,
                    .TipReceptie = If(k = perChain - 1, "Final", "Partial"),
                    .Stergere = isDeletion,
                    .Ignorat = False,
                    .Blocat = k < frozen
                }
                If inst.Blocat Then
                    inst.Motive.Add("Instantaneul e cuprins într-o ordonanțare deja emisă.")
                End If
                inst.Linii.Add(New LinieInstantaneu() With {
                    .CodIndicator = "20.01.0" & ((r Mod 9) + 1).ToString(CultureInfo.InvariantCulture),
                    .CodAi = "A" & r.ToString(CultureInfo.InvariantCulture),
                    .Valoare = total
                })

                state.Instantanee.Add(inst)
                last = total
                idrh += 1
            Next

            ' Every third receipt is left with a header its chain does not match, so the surface
            ' has to show the warning end mark as well as the plain one.
            rec.SumaAntet = If(r Mod 3 = 0, last + 250.0, last)
            state.Receptii.Add(rec)
        Next

        ' The loose ones: on no receipt at all. Every third is marked «records no change» (F17),
        ' which is a deliberate setting-aside and not an untouched row — two different shapes.
        Dim span As Integer = Math.Max(1, receipts * 3 + perChain * 2)
        For j As Integer = 0 To loose - 1
            Dim inst As New InstantaneuLegat() With {
                .Idrh = idrh,
                .Idrr = 0,
                .DataH = origin.AddDays((j * span) \ Math.Max(1, loose)).AddHours(10 + (j Mod 6)),
                .Descriere = $"Instantaneu neașezat {j + 1}",
                .Total = 500 + j * 175,
                .Stergere = False,
                .Ignorat = (j Mod 3 = 0),
                .Blocat = False
            }
            state.Instantanee.Add(inst)
            idrh += 1
        Next

        ' The payments. Spread across the whole span, because the point of a guide is where it
        ' falls RELATIVE to the snapshots — a payment outside the span is simply not drawn.
        For p As Integer = 0 To payments - 1
            state.Plati.Add(New PlataAsociere() With {
                .DataPlata = origin.AddDays(((p + 1) * span) \ (payments + 1)).AddHours(12),
                .Suma = 900 + p * 320,
                .NrOp = "OP" & (p + 1).ToString(CultureInfo.InvariantCulture)
            })
        Next

        Return state
    End Function

    ' ══════════════════════════════════════════════════════════════════════════
    ' The two surfaces — same construction as AsociereForm
    ' ══════════════════════════════════════════════════════════════════════════

    ''' <summary>Rebuilds the surfaces asked for and returns how long it took, in ms.</summary>
    Private Function Rebuild(lanes As Boolean, chart As Boolean) As Long
        Dim sw As Stopwatch = Stopwatch.StartNew()
        Try
            If lanes Then BuildLanes()
            If chart Then BuildChart()
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.Rebuild", ex)
            Note("EROARE la reconstrucție: " & ex.Message)
        End Try
        Return sw.ElapsedMilliseconds
    End Function

    ''' <summary>
    ''' One lane per receipt, one marker per snapshot, the loose ones on a lane of their own, and
    ''' the payments as guides on both surfaces. Same order and same rules as the real form.
    ''' </summary>
    Private Sub BuildLanes()
        Me.lanes.BeginUpdate()
        Try
            Me.lanes.ClearLanes()
            Me.lanes.ClearGuides()
            _laneByIdrr.Clear()
            _markerByIdrh.Clear()
            If _state Is Nothing Then Return

            Dim i As Integer = 0
            For Each rec As ReceptiePropusa In _state.Receptii.OrderBy(Function(r) r.DataR).ThenBy(Function(r) r.Idrr)
                Dim chain As List(Of InstantaneuLegat) = ChainOf(rec)

                Dim lane As KBotLane = Me.lanes.AddLane(SeriesKey(rec), ReceiptCaption(rec))
                lane.Tag = rec
                lane.Tooltip = LaneTooltip(rec, chain)
                ' Written EXPLICITLY, not left to the control: the same receipt has a line in the
                ' chart, and a colour nobody wrote down is one the chart cannot be told about.
                lane.LaneColor = Me.lanes.AutoColor(i)
                lane.EndMark = EndMarkOf(rec, chain)
                _laneByIdrr(rec.Idrr) = lane

                For Each inst As InstantaneuLegat In chain
                    Dim marker As KBotLaneMarker = lane.AddMarker(inst.DataH, Money(inst.Total))
                    marker.Tag = inst
                    marker.Tooltip = SnapshotTooltip(inst)
                    marker.Style = MarkerStyleOf(inst, placed:=True)
                    _markerByIdrh(inst.Idrh) = marker
                Next
                i += 1
            Next

            Dim free As List(Of InstantaneuLegat) =
                _state.Instantanee.Where(Function(x) PlacementOf(x) = 0).
                                   OrderBy(Function(x) x.DataH).ThenBy(Function(x) x.Idrh).ToList()

            Dim looseLane As KBotLane = Me.lanes.AddLane(LOOSE_KEY, $"Neașezate ({free.Count})")
            looseLane.SeparatorAbove = True
            looseLane.Tooltip = "Instantaneele care nu stau pe nicio recepție." & Environment.NewLine &
                                "Trage un marcaj aici ca să-l desprinzi de recepția lui."
            For j As Integer = 0 To free.Count - 1
                Dim inst As InstantaneuLegat = free(j)
                Dim marker As KBotLaneMarker = looseLane.AddMarker(inst.DataH, Money(inst.Total))
                marker.Tag = inst
                marker.Tooltip = SnapshotTooltip(inst)
                marker.Style = MarkerStyleOf(inst, placed:=False)
                marker.MarkerColor = Me.lanes.AutoColor(j)
                _markerByIdrh(inst.Idrh) = marker
            Next

            ColourMarkersByChange()
            BuildGuides()
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.BuildLanes", ex)
        Finally
            Me.lanes.EndUpdate()
        End Try
    End Sub

    ''' <summary>
    ''' Green where the snapshot raised the receipt, red where it lowered it, and no colour at
    ''' all where it changed nothing. The bottom lane keeps its own colours: its markers are not
    ''' a chain, so «it went up» would be a claim about two unrelated things.
    ''' </summary>
    Private Sub ColourMarkersByChange()
        Dim palette As ThemePalette = ThemeManager.Current?.Palette
        If palette Is Nothing Then Return

        For Each lane As KBotLane In Me.lanes.Lanes
            If String.Equals(lane.Key, LOOSE_KEY, StringComparison.Ordinal) Then Continue For

            Dim previous As Double = 0
            For Each marker As KBotLaneMarker In lane.Markers
                Dim inst As InstantaneuLegat = TryCast(marker.Tag, InstantaneuLegat)
                If inst Is Nothing Then Continue For
                If inst.Total > previous Then
                    marker.MarkerColor = palette.SuccessColor
                ElseIf inst.Total < previous Then
                    marker.MarkerColor = palette.ErrorColor
                Else
                    marker.MarkerColor = Color.Empty
                End If
                previous = inst.Total
            Next
        Next
    End Sub

    ''' <summary>
    ''' The payments, as a vertical line on BOTH surfaces, each carrying what the commitment was
    ''' worth at that moment against what had already been paid — §1.3, the reason the placement
    ''' matters at all.
    ''' </summary>
    ''' <remarks>
    ''' Two guide objects built in the SAME loop from the same payment, never one object added to
    ''' both collections: a guide has one owner, the surface that repaints it, and the second
    ''' surface would steal it from the first.
    ''' </remarks>
    Private Sub BuildGuides()
        If _state Is Nothing Then Return

        ' The chains ONCE, not one set per payment: twenty receipts by twenty payments is four
        ' hundred walks through every snapshot for an answer the first walk already had.
        Dim chains As List(Of List(Of InstantaneuLegat)) =
            _state.Receptii.Select(Function(r) ChainOf(r)).Where(Function(l) l.Count > 0).ToList()

        Dim paidBefore As Double = 0
        For Each pay As PlataAsociere In _state.Plati.OrderBy(Function(p) p.DataPlata)
            Dim total As Double = 0
            For Each chain As List(Of InstantaneuLegat) In chains
                total += ValueAt(chain, pay.DataPlata)
            Next

            Dim header As String = $"Plată {pay.DataPlata:dd.MM.yyyy} · {Money(pay.Suma)}"
            Dim body As String = $"Angajamentul valora {Money(total)} la data plății." & Environment.NewLine &
                                 $"Plăți anterioare: {Money(paidBefore)}." & Environment.NewLine &
                                 $"Disponibil: {Money(total - paidBefore - pay.Suma)}."

            Dim onLanes As KBotChartGuide = Me.lanes.AddGuide(pay.DataPlata, header)
            onLanes.Tooltip = body
            onLanes.Tag = pay

            Dim onChart As KBotChartGuide = Me.chart.AddGuide(pay.DataPlata, header)
            onChart.Tooltip = body
            onChart.Tag = pay

            paidBefore += pay.Suma
        Next
    End Sub

    ''' <summary>The chart, in whichever of its two readings is selected.</summary>
    Private Sub BuildChart()
        Me.chart.BeginUpdate()
        Try
            Me.chart.ClearSeries()
            If _state Is Nothing Then Return
            If String.Equals(Me.chart.SelectedTabKey, TAB_COMMITMENT, StringComparison.Ordinal) Then
                BuildCommitmentChart()
            Else
                BuildReceiptChart()
            End If
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.BuildChart", ex)
        Finally
            Me.chart.EndUpdate()
        End Try
    End Sub

    ''' <summary>One line: the chain of the selected receipt, each point in its own colour.</summary>
    Private Sub BuildReceiptChart()
        If _selectedReceipt Is Nothing Then
            Me.chart.EmptyText = "Nicio recepție aleasă."
            Return
        End If

        Dim chain As List(Of InstantaneuLegat) = ChainOf(_selectedReceipt)
        If chain.Count = 0 Then
            Me.chart.EmptyText = "Recepția aleasă nu are niciun instantaneu."
            Return
        End If

        Dim series As KBotChartSeries = Me.chart.AddSeries(SeriesKey(_selectedReceipt),
                                                           ReceiptCaption(_selectedReceipt))
        series.Emphasis = True
        series.FillArea = True
        series.LineMode = KBotChartLineMode.Step

        Dim i As Integer = 0
        For Each inst As InstantaneuLegat In chain
            AddPoint(series, inst).PointColor = Me.chart.AutoColor(i)
            i += 1
        Next
    End Sub

    ''' <summary>One line per receipt, plus the thicker total line.</summary>
    Private Sub BuildCommitmentChart()
        Me.chart.EmptyText = "Angajamentul nu are niciun instantaneu așezat."

        Dim chains As New List(Of List(Of InstantaneuLegat))()
        For Each rec As ReceptiePropusa In _state.Receptii.OrderBy(Function(r) r.DataR).ThenBy(Function(r) r.Idrr)
            Dim chain As List(Of InstantaneuLegat) = ChainOf(rec)
            If chain.Count = 0 Then Continue For
            chains.Add(chain)

            Dim series As KBotChartSeries = Me.chart.AddSeries(SeriesKey(rec), ReceiptCaption(rec))
            series.LineColor = Me.chart.AutoColor(chains.Count - 1)
            series.FillArea = _selectedReceipt IsNot Nothing AndAlso rec.Idrr = _selectedReceipt.Idrr
            series.LineMode = KBotChartLineMode.Step
            For Each inst As InstantaneuLegat In chain
                AddPoint(series, inst)
            Next
        Next

        BuildTotalSeries(chains)
    End Sub

    ''' <summary>
    ''' The total: one point per distinct moment in the whole picture, each receipt contributing
    ''' the value of its own last snapshot up to then. With a single chain there is no total to
    ''' draw — it would be the same line twice.
    ''' </summary>
    Private Sub BuildTotalSeries(chains As List(Of List(Of InstantaneuLegat)))
        If chains.Count < 2 Then Return

        Dim moments As List(Of Date) =
            chains.SelectMany(Function(l) l).Select(Function(i) i.DataH).Distinct().OrderBy(Function(d) d).ToList()
        If moments.Count = 0 Then Return

        Dim series As KBotChartSeries = Me.chart.AddSeries(TOTAL_KEY, "Total angajament")
        series.Emphasis = True
        series.LineMode = KBotChartLineMode.Step
        ' Deliberately NOT one of AutoColor's: that set belongs to the receipts, and the total is
        ' not one more receipt.
        Dim palette As ThemePalette = ThemeManager.Current?.Palette
        If palette IsNot Nothing Then series.LineColor = palette.TextColor

        For Each moment As Date In moments
            Dim total As Double = 0
            For Each chain As List(Of InstantaneuLegat) In chains
                total += ValueAt(chain, moment)
            Next
            Dim point As KBotChartPoint = series.AddPoint(moment, total)
            point.TooltipHeader = "Total angajament"
            point.TooltipText = $"{moment:dd.MM.yyyy HH:mm} · {Money(total)}"
        Next
    End Sub

    Private Function AddPoint(series As KBotChartSeries, inst As InstantaneuLegat) As KBotChartPoint
        Dim point As KBotChartPoint = series.AddPoint(inst.DataH, inst.Total)
        point.Tag = inst
        point.TooltipHeader = inst.Descriere
        point.TooltipText = $"{inst.DataH:dd.MM.yyyy HH:mm} · {Money(inst.Total)}"
        If inst.Blocat Then point.TooltipFooter = "Nu se mai poate muta."
        Return point
    End Function

    ' ══════════════════════════════════════════════════════════════════════════
    ' Rules read back out of the state
    ' ══════════════════════════════════════════════════════════════════════════

    ''' <summary>Where a snapshot sits after the local moves. 0 = on no receipt.</summary>
    Private Function PlacementOf(inst As InstantaneuLegat) As Integer
        If inst Is Nothing Then Return 0
        Dim moved As Integer
        If _placement.TryGetValue(inst.Idrh, moved) Then Return moved
        Return inst.Idrr
    End Function

    ''' <summary>The chain of a receipt after the local moves, along its own time axis.</summary>
    Private Function ChainOf(rec As ReceptiePropusa) As List(Of InstantaneuLegat)
        If _state Is Nothing OrElse rec Is Nothing Then Return New List(Of InstantaneuLegat)()
        Return _state.Instantanee.Where(Function(i) PlacementOf(i) = rec.Idrr).
                                  OrderBy(Function(i) i.DataH).ThenBy(Function(i) i.Idrh).ToList()
    End Function

    ''' <summary>What one chain was worth at a given moment.</summary>
    Private Shared Function ValueAt(chain As List(Of InstantaneuLegat), moment As Date) As Double
        Dim value As Double = 0
        For Each inst As InstantaneuLegat In chain
            If inst.DataH > moment Then Exit For
            value = If(inst.Stergere AndAlso inst.DataH < moment, 0.0, inst.Total)
        Next
        Return value
    End Function

    ''' <summary>
    ''' What the shape of a marker says. The order matters: the padlock beats the deletion row,
    ''' because at a marker that will not move the first question is why it will not move.
    ''' </summary>
    Private Shared Function MarkerStyleOf(inst As InstantaneuLegat, placed As Boolean) As KBotLaneMarkerStyle
        If Not placed Then
            Return If(inst.Ignorat, KBotLaneMarkerStyle.NoChange, KBotLaneMarkerStyle.Loose)
        End If
        If inst.Blocat Then Return KBotLaneMarkerStyle.Locked
        If inst.Stergere Then Return KBotLaneMarkerStyle.Deletion
        Return KBotLaneMarkerStyle.Normal
    End Function

    Private Shared Function EndMarkOf(rec As ReceptiePropusa, chain As List(Of InstantaneuLegat)) As KBotLaneEndMark
        If rec Is Nothing OrElse chain Is Nothing OrElse chain.Count = 0 Then Return KBotLaneEndMark.None
        Dim last As InstantaneuLegat = chain(chain.Count - 1)
        If last.Stergere Then Return KBotLaneEndMark.None
        If Math.Round(last.Total, 2) = Math.Round(rec.SumaAntet, 2) Then Return KBotLaneEndMark.Ok
        Return KBotLaneEndMark.Warning
    End Function

    Private Shared Function SeriesKey(rec As ReceptiePropusa) As String
        Return "R" & rec.Idrr.ToString(CultureInfo.InvariantCulture)
    End Function

    Private Shared Function ReceiptCaption(rec As ReceptiePropusa) As String
        Return $"Recepția {rec.Idrr} · {rec.DataR:dd.MM.yyyy}"
    End Function

    Private Shared Function LaneTooltip(rec As ReceptiePropusa, chain As List(Of InstantaneuLegat)) As String
        Dim sb As New Text.StringBuilder()
        sb.AppendLine(ReceiptCaption(rec))
        sb.AppendLine($"Antet: {Money(rec.SumaAntet)}")
        sb.AppendLine()
        sb.AppendLine($"{chain.Count} instantanee pe bandă.")
        Return sb.ToString().TrimEnd()
    End Function

    Private Shared Function SnapshotTooltip(inst As InstantaneuLegat) As String
        Dim sb As New Text.StringBuilder()
        sb.AppendLine($"{inst.DataH:dd.MM.yyyy HH:mm:ss} · {Money(inst.Total)}")
        If Not String.IsNullOrWhiteSpace(inst.Descriere) Then sb.AppendLine(inst.Descriere)
        Dim indicators As String = String.Join(", ", inst.Indicatori().OrderBy(Function(x) x))
        If indicators <> "" Then sb.AppendLine($"Indicatori: {indicators}")
        If inst.Blocat Then
            sb.AppendLine()
            sb.AppendLine("NU SE MAI POATE MUTA:")
            For Each reason As String In inst.Motive
                sb.AppendLine("• " & reason)
            Next
        End If
        Return sb.ToString().TrimEnd()
    End Function

    Private Shared Function Money(v As Double) As String
        Return v.ToString("N2", _roCulture)
    End Function

    ' ══════════════════════════════════════════════════════════════════════════
    ' Measuring
    ' ══════════════════════════════════════════════════════════════════════════

    ''' <summary>
    ''' Paints each surface N times and reports milliseconds per frame, separately.
    ''' </summary>
    ''' <remarks>
    ''' <c>Invalidate</c> + <c>Update</c>, not <c>Refresh</c> on the form: the two surfaces have
    ''' to be timed APART, because a number covering both cannot say which one is the slow one —
    ''' which is the only question the bench exists to answer. The layout is already valid on
    ''' the second frame onwards, so what this measures is the PAINT, not the arithmetic that
    ''' feeds it; the rebuild is timed on its own, below.
    ''' </remarks>
    Private Sub OnMeasure(sender As Object, e As EventArgs) Handles btnMeasure.Click
        Try
            Dim n As Integer = CInt(numFrames.Value)

            Dim chartMs As Double = PaintFrames(Me.chart, n)
            Dim laneMs As Double = PaintFrames(Me.lanes, n)
            Dim rebuildChart As Long = Rebuild(lanes:=False, chart:=True)
            Dim rebuildLanes As Long = Rebuild(lanes:=True, chart:=False)

            Note($"repictare ({n} cadre): grafic {chartMs:F2} ms/cadru ({Fps(chartMs)}), " &
                 $"benzi {laneMs:F2} ms/cadru ({Fps(laneMs)})")
            Note($"reconstrucție: grafic {rebuildChart} ms · benzi {rebuildLanes} ms")
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnMeasure", ex)
            Note("EROARE la măsurare: " & ex.Message)
        End Try
    End Sub

    Private Shared Function PaintFrames(target As Control, count As Integer) As Double
        ' One frame thrown away first: the very first paint after a rebuild also builds whatever
        ' the control caches, and charging that to the average would flatter every later frame.
        target.Invalidate()
        target.Update()

        Dim sw As Stopwatch = Stopwatch.StartNew()
        For i As Integer = 1 To count
            target.Invalidate()
            target.Update()
        Next
        sw.Stop()
        Return sw.Elapsed.TotalMilliseconds / Math.Max(1, count)
    End Function

    Private Shared Function Fps(msPerFrame As Double) As String
        If msPerFrame <= 0 Then Return "—"
        Return (1000.0 / msPerFrame).ToString("F0", CultureInfo.InvariantCulture) & " cadre/s"
    End Function

    Private Sub OnAnimateChanged(sender As Object, e As EventArgs) Handles chkAnimate.CheckedChanged
        Try
            _frames = 0
            _fpsClock.Restart()
            If chkAnimate.Checked Then
                _animate.Start()
            Else
                _animate.Stop()
                lblFps.Text = "—"
            End If
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnAnimateChanged", ex)
        End Try
    End Sub

    ''' <summary>
    ''' One frame of both surfaces per tick. The guard is what makes the number honest: a tick
    ''' arriving while the previous frame is still painting must be dropped, not queued behind it.
    ''' </summary>
    Private Sub OnAnimateTick(sender As Object, e As EventArgs) Handles _animate.Tick
        If _animating Then Return
        _animating = True
        Try
            Me.chart.Invalidate()
            Me.chart.Update()
            Me.lanes.Invalidate()
            Me.lanes.Update()
            _frames += 1

            If _fpsClock.ElapsedMilliseconds >= 500 Then
                Dim rate As Double = _frames * 1000.0 / _fpsClock.ElapsedMilliseconds
                lblFps.Text = rate.ToString("F1", CultureInfo.InvariantCulture) & " cadre/s (ambele)"
                _frames = 0
                _fpsClock.Restart()
            End If
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnAnimateTick", ex)
        Finally
            _animating = False
        End Try
    End Sub

    ' ══════════════════════════════════════════════════════════════════════════
    ' Handlers
    ' ══════════════════════════════════════════════════════════════════════════

    Private Sub OnGenerate(sender As Object, e As EventArgs) Handles btnGenerate.Click
        Try
            Regenerate()
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnGenerate", ex)
            Note("EROARE la generare: " & ex.Message)
        End Try
    End Sub

    Private Sub OnTabSelected(tabKey As String) Handles chart.TabSelected
        Try
            Note($"grafic → «{tabKey}», reconstruit în {Rebuild(lanes:=False, chart:=True)} ms")
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnTabSelected", ex)
        End Try
    End Sub

    ''' <summary>A point stands for a snapshot; clicking one selects its receipt, as in the form.</summary>
    Private Sub OnPointClicked(seriesKey As String, pointIndex As Integer) Handles chart.PointClicked
        Try
            If String.Equals(seriesKey, TOTAL_KEY, StringComparison.Ordinal) Then Return
            Dim series As KBotChartSeries = Me.chart.FindSeries(seriesKey)
            If series Is Nothing OrElse pointIndex < 0 OrElse pointIndex >= series.Points.Count Then Return
            Dim inst As InstantaneuLegat = TryCast(series.Points(pointIndex).Tag, InstantaneuLegat)
            If inst Is Nothing Then Return
            Note($"punct: instantaneul {inst.Idrh} · {Money(inst.Total)}")
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnPointClicked", ex)
        End Try
    End Sub

    ''' <summary>A frozen snapshot cannot be dragged at all — the padlock is not decoration.</summary>
    Private Sub OnDragStarting(sender As Object, e As LaneDragStartEventArgs) Handles lanes.MarkerDragStarting
        Try
            Dim inst As InstantaneuLegat = TryCast(e.Marker?.Tag, InstantaneuLegat)
            If inst Is Nothing OrElse inst.Blocat Then
                e.Cancel = True
                If inst IsNot Nothing Then Note($"instantaneul {inst.Idrh} e blocat, nu se trage")
            End If
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnDragStarting", ex)
            e.Cancel = True
        End Try
    End Sub

    ''' <summary>Refusal is the default; this says yes to anything that actually moves.</summary>
    Private Sub OnMarkerDragOver(sender As Object, e As LaneDragOverEventArgs) Handles lanes.MarkerDragOver
        Try
            Dim inst As InstantaneuLegat = TryCast(e.Marker?.Tag, InstantaneuLegat)
            If inst Is Nothing OrElse e.Target Is Nothing Then Return
            If inst.Blocat Then
                e.Reason = "Instantaneul e blocat de o ordonanțare."
                Return
            End If
            If e.From IsNot Nothing AndAlso String.Equals(e.From.Key, e.Target.Key, StringComparison.Ordinal) Then
                e.Reason = "E deja pe banda asta."
                Return
            End If
            e.Allow = True
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnMarkerDragOver", ex)
        End Try
    End Sub

    ''' <summary>
    ''' The move itself: the control never moves a marker, it only says a drop happened. This is
    ''' also the path that lags in the real form, so the rebuild it triggers is timed.
    ''' </summary>
    Private Sub OnDropped(sender As Object, e As LaneDropEventArgs) Handles lanes.MarkerDropped
        Try
            Dim inst As InstantaneuLegat = TryCast(e.Marker?.Tag, InstantaneuLegat)
            If inst Is Nothing OrElse e.Target Is Nothing Then Return

            Dim target As Integer = 0
            If Not String.Equals(e.Target.Key, LOOSE_KEY, StringComparison.Ordinal) Then
                Dim rec As ReceptiePropusa = TryCast(e.Target.Tag, ReceptiePropusa)
                If rec Is Nothing Then Return
                target = rec.Idrr
            End If

            _placement(inst.Idrh) = target
            Dim laneMs As Long = Rebuild(lanes:=True, chart:=False)
            Dim chartMs As Long = Rebuild(lanes:=False, chart:=True)
            Note($"mutat {inst.Idrh} → {If(target = 0, "neașezate", "R" & target.ToString(CultureInfo.InvariantCulture))} " &
                 $"· benzi {laneMs} ms · grafic {chartMs} ms")
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnDropped", ex)
            Note("EROARE la mutare: " & ex.Message)
        End Try
    End Sub

    Private Sub OnEnlarge() Handles lanes.EnlargeRequested
        Try
            Note("s-a cerut fereastra mare (bancul nu o deschide)")
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.OnEnlarge", ex)
        End Try
    End Sub

    Private Sub OnClassic(sender As Object, e As EventArgs) Handles btnClassic.Click
        SwitchScheme(BuiltInSchemes.Classic())
    End Sub

    Private Sub OnDark(sender As Object, e As EventArgs) Handles btnDark.Click
        SwitchScheme(BuiltInSchemes.Dark())
    End Sub

    Private Sub OnModern(sender As Object, e As EventArgs) Handles btnModern.Click
        SwitchScheme(BuiltInSchemes.Modern())
    End Sub

    ''' <summary>
    ''' The scheme decides the marker colours and the total line, so both surfaces are rebuilt
    ''' after it changes — repainting alone would leave yesterday's greens on today's palette.
    ''' </summary>
    Private Sub SwitchScheme(scheme As ThemeScheme)
        Try
            ThemeManager.SetScheme(scheme)
            Rebuild(lanes:=True, chart:=True)
            Note("schema → " & scheme.Name)
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.SwitchScheme", ex)
        End Try
    End Sub

    Private Sub Note(text As String)
        Try
            _log?.Invoke(text)
            lstLog.Items.Insert(0, DateTime.Now.ToString("HH:mm:ss", CultureInfo.InvariantCulture) & "  " & text)
        Catch ex As Exception
            GlobalErrorLog.Write("AsociereStressForm.Note", ex)
        End Try
    End Sub

End Class
