-- Query: qCOMP_D
-- Type: Select

SELECT U.D_IDP, U.D_IDG, U.D_GRUPA, U.D_NUME, Sum(U.D_SOLD) AS D_SOLD, Sum(U.D_REST) AS D_REST
FROM (SELECT IDP as D_IDP, IDG as D_IDG, GRUPA as D_GRUPA, NUME as D_NUME, SFD as D_SOLD, SFD as D_REST FROM SS_Buget WHERE ROUND(SFD,2) > 0 AND IDL = [LIDL] 
UNION ALL 
SELECT COMP.IDP_D AS D_IDP, Grupe.IDG AS D_IDG, Grupe.Grupa AS D_GRUPA, Platitori.Nume AS D_NUME, -1*[SUMA] AS D_SOLD, -1*[SUMA] AS D_REST
FROM (Grupe INNER JOIN Platitori ON Grupe.IDG = Platitori.IDG) INNER JOIN [COMP] ON Platitori.IDP = COMP.IDP_D
)  AS U
GROUP BY U.D_IDP, U.D_IDG, U.D_GRUPA, U.D_NUME
ORDER BY U.D_GRUPA, U.D_NUME;
