-- SLICE-ADE3-01. Tables of the kindergarten module (prefix AD_), for AVACONT_SURSA. Charset matches the server (utf8mb3).

-- No USE, DROP, data seeds, or changes to existing business tables.

-- Legacy monetary types are preserved. Server execution is not locally validated.

CREATE TABLE IF NOT EXISTS `AD_Grupe` (
  `IDG` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Grupa` VARCHAR(50) NULL,
  `Educator` VARCHAR(50) NULL,
  `Version` BIGINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_ValoriTaxe` (
  `IDV` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `TaxaZilnica` DOUBLE NULL DEFAULT 0,
  `Activ` BOOLEAN NULL DEFAULT 0,
  `Expl` VARCHAR(255) NULL,
  `Version` BIGINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_LunaD` (
  `IDL` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDV` INT NULL DEFAULT NULL,
  `Luna` INT NULL DEFAULT 0,
  `Anul` INT NULL DEFAULT 0,
  `LunaT` VARCHAR(255) NULL,
  `LA` VARCHAR(255) NULL,
  `Inchisa` BOOLEAN NULL DEFAULT 0,
  `ZileLuna` INT NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDV` (`IDV`),
  CONSTRAINT `fk_LunaD_IDV` FOREIGN KEY (`IDV`) REFERENCES `AD_ValoriTaxe` (`IDV`) ON DELETE RESTRICT ON UPDATE CASCADE,
  UNIQUE KEY `uq_Luna_Anul` (`Luna`,`Anul`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_Platitori` (
  `IDP` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDG` INT NULL DEFAULT NULL,
  `Nume` VARCHAR(255) NULL,
  `CNP` VARCHAR(255) NULL,
  `Plecat` BOOLEAN NULL DEFAULT 0,
  `SI` INT NULL DEFAULT 0,
  `DataIntrare` DATETIME NULL,
  `DataIesire` DATETIME NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDG` (`IDG`),
  CONSTRAINT `fk_Platitori_IDG` FOREIGN KEY (`IDG`) REFERENCES `AD_Grupe` (`IDG`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_Platitori_sub` (
  `IDS` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDP` INT NULL DEFAULT NULL,
  `Nume` VARCHAR(50) NULL,
  `Adresa` VARCHAR(255) NULL,
  `CUI` VARCHAR(255) NULL,
  `Cont` VARCHAR(255) NULL,
  `Banca` VARCHAR(255) NULL,
  `EMail` VARCHAR(255) NULL,
  `TrimiteMail` BOOLEAN NULL DEFAULT 0,
  `Activ` BOOLEAN NULL DEFAULT 0,
  `CNP_Platitor` VARCHAR(255) NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDP` (`IDP`),
  CONSTRAINT `fk_Platitori_sub_IDP` FOREIGN KEY (`IDP`) REFERENCES `AD_Platitori` (`IDP`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_Prezenta` (
  `IDZ` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDP` INT NULL DEFAULT NULL,
  `IDL` INT NULL DEFAULT NULL,
  `IDV` INT NULL DEFAULT NULL,
  `IDG` INT NULL DEFAULT NULL,
  `ZilePrezenta` INT NULL DEFAULT 0,
  `ValoareContract` DOUBLE NULL DEFAULT 0,
  `ValoareTotala` INT NULL DEFAULT 0,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDP` (`IDP`),
  INDEX `ix_IDL` (`IDL`),
  INDEX `ix_IDG` (`IDG`),
  INDEX `ix_IDV` (`IDV`),
  CONSTRAINT `fk_Prezenta_IDP` FOREIGN KEY (`IDP`) REFERENCES `AD_Platitori` (`IDP`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Prezenta_IDL` FOREIGN KEY (`IDL`) REFERENCES `AD_LunaD` (`IDL`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Prezenta_IDV` FOREIGN KEY (`IDV`) REFERENCES `AD_ValoriTaxe` (`IDV`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Prezenta_IDG` FOREIGN KEY (`IDG`) REFERENCES `AD_Grupe` (`IDG`) ON DELETE RESTRICT ON UPDATE CASCADE,
  UNIQUE KEY `uq_IDP_IDL` (`IDP`,`IDL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_Plati` (
  `IDPL` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDP` INT NULL DEFAULT NULL,
  `IDZ` INT NULL DEFAULT NULL,
  `IDS` INT NULL DEFAULT NULL,
  `IDL` INT NULL DEFAULT NULL,
  `Data` DATETIME NULL,
  `Plata` INT NULL DEFAULT 0,
  `TIP` INT NULL,
  `Anulata` BOOLEAN NULL DEFAULT 0,
  `Valid` BOOLEAN NULL DEFAULT 0,
  `Motivul` VARCHAR(255) NULL,
  `OriginMonth` INT NULL,
  `OriginYear` INT NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDP` (`IDP`),
  INDEX `ix_IDL` (`IDL`),
  INDEX `ix_IDZ` (`IDZ`),
  INDEX `ix_IDS` (`IDS`),
  CONSTRAINT `fk_Plati_IDP` FOREIGN KEY (`IDP`) REFERENCES `AD_Platitori` (`IDP`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Plati_IDZ` FOREIGN KEY (`IDZ`) REFERENCES `AD_Prezenta` (`IDZ`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_Plati_IDS` FOREIGN KEY (`IDS`) REFERENCES `AD_Platitori_sub` (`IDS`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Plati_IDL` FOREIGN KEY (`IDL`) REFERENCES `AD_LunaD` (`IDL`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_Chitante` (
  `IDC` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDPL` INT NULL DEFAULT NULL,
  `Data` DATETIME NULL,
  `Serie` VARCHAR(50) NULL,
  `Numar` INT NULL DEFAULT 0,
  `Explicatie` VARCHAR(255) NULL,
  `Anulata` BOOLEAN NULL,
  `IDL` INT NULL DEFAULT NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDL` (`IDL`),
  INDEX `ix_IDPL` (`IDPL`),
  CONSTRAINT `fk_Chitante_IDPL` FOREIGN KEY (`IDPL`) REFERENCES `AD_Plati` (`IDPL`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Chitante_IDL` FOREIGN KEY (`IDL`) REFERENCES `AD_LunaD` (`IDL`) ON DELETE SET NULL ON UPDATE CASCADE,
  UNIQUE KEY `uq_Serie_Numar` (`Serie`,`Numar`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_AlteDoc` (
  `IDA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDPL` INT NULL DEFAULT NULL,
  `NrDoc` VARCHAR(255) NULL,
  `FelDoc` VARCHAR(255) NULL,
  `DataDoc` DATETIME NULL,
  `Anulata` BOOLEAN NULL DEFAULT 0,
  `IDL` INT NULL DEFAULT NULL,
  `Explicatie` VARCHAR(255) NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDL` (`IDL`),
  INDEX `ix_IDPL` (`IDPL`),
  CONSTRAINT `fk_AlteDoc_IDPL` FOREIGN KEY (`IDPL`) REFERENCES `AD_Plati` (`IDPL`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_AlteDoc_IDL` FOREIGN KEY (`IDL`) REFERENCES `AD_LunaD` (`IDL`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_Retur` (
  `IDR` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDP` INT NULL DEFAULT NULL,
  `IDZ` INT NULL DEFAULT NULL,
  `IDL` INT NULL DEFAULT NULL,
  `IDS` INT NULL DEFAULT NULL,
  `Data` DATETIME NULL,
  `Explicatie` VARCHAR(255) NULL,
  `Anulat` BOOLEAN NULL DEFAULT 0,
  `NrDoc` VARCHAR(255) NULL,
  `Suma` DOUBLE NULL,
  `OriginMonth` INT NULL,
  `OriginYear` INT NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDP` (`IDP`),
  INDEX `ix_IDL` (`IDL`),
  INDEX `ix_IDZ` (`IDZ`),
  INDEX `ix_IDS` (`IDS`),
  CONSTRAINT `fk_Retur_IDP` FOREIGN KEY (`IDP`) REFERENCES `AD_Platitori` (`IDP`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Retur_IDZ` FOREIGN KEY (`IDZ`) REFERENCES `AD_Prezenta` (`IDZ`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_Retur_IDS` FOREIGN KEY (`IDS`) REFERENCES `AD_Platitori_sub` (`IDS`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_Retur_IDL` FOREIGN KEY (`IDL`) REFERENCES `AD_LunaD` (`IDL`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS `AD_SS_Buget` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `IDG` INT NULL DEFAULT NULL,
  `IDP` INT NULL DEFAULT NULL,
  `IDL` INT NULL DEFAULT NULL,
  `IDZ` INT NULL DEFAULT NULL,
  `Luna` VARCHAR(255) NULL,
  `Anul` INT NULL,
  `Nume` VARCHAR(255) NULL,
  `CNP` VARCHAR(255) NULL,
  `ZilePrezenta` INT NULL,
  `SID` INT NULL DEFAULT 0,
  `SIC` INT NULL DEFAULT 0,
  `ValoareContract` DOUBLE NULL,
  `ValoareTotala` INT NULL,
  `Plata` DOUBLE NULL,
  `Restanta` DOUBLE NULL,
  `Compensare` DOUBLE NULL,
  `Anticipat` DOUBLE NULL,
  `Plati` INT NULL DEFAULT 0,
  `Retur` INT NULL DEFAULT 0,
  `SFD` INT NULL DEFAULT 0,
  `SFC` INT NULL DEFAULT 0,
  `Detalii` LONGTEXT NULL,
  `Plecat` BOOLEAN NULL DEFAULT 0,
  `Educator` VARCHAR(255) NULL,
  `Grupa` VARCHAR(255) NULL,
  `Version` BIGINT NOT NULL DEFAULT 1,
  INDEX `ix_IDP` (`IDP`),
  INDEX `ix_IDL` (`IDL`),
  INDEX `ix_IDZ` (`IDZ`),
  INDEX `ix_IDG` (`IDG`),
  CONSTRAINT `fk_SS_Buget_IDG` FOREIGN KEY (`IDG`) REFERENCES `AD_Grupe` (`IDG`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_SS_Buget_IDP` FOREIGN KEY (`IDP`) REFERENCES `AD_Platitori` (`IDP`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_SS_Buget_IDL` FOREIGN KEY (`IDL`) REFERENCES `AD_LunaD` (`IDL`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_SS_Buget_IDZ` FOREIGN KEY (`IDZ`) REFERENCES `AD_Prezenta` (`IDZ`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS AD_Lock (ID INT PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

INSERT IGNORE INTO AD_Lock (ID) VALUES (1);


CREATE TABLE IF NOT EXISTS AD_Operations (RequestKey VARCHAR(100) PRIMARY KEY, Fingerprint CHAR(64) NOT NULL, Result LONGTEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

CREATE TABLE IF NOT EXISTS AD_Settings (SettingKey VARCHAR(64) PRIMARY KEY, SettingValue VARCHAR(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

INSERT IGNORE INTO AD_Settings (SettingKey, SettingValue) VALUES ('BlockReopenWithMovements', '1');

CREATE TABLE IF NOT EXISTS AD_Imports (SourceHash CHAR(64) PRIMARY KEY, SourceFile VARCHAR(255) NOT NULL, Manifest LONGTEXT NOT NULL, Result LONGTEXT NOT NULL, ImportedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
